"""empty message

Revision ID: 6dcc738e8708
Revises: 84ab17c5c709
Create Date: 2023-11-21 19:41:50.034441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dcc738e8708'
down_revision = '84ab17c5c709'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_book', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'book', ['id_book'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_book')

    # ### end Alembic commands ###
